// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOryXz6OeSCPPJqNDthEnOyv1-3bwftqQ',
    appId: '1:188574300841:web:6e57257c4f33b6ef4d87b8',
    messagingSenderId: '188574300841',
    projectId: 'learning-app-c5b3f',
    authDomain: 'learning-app-c5b3f.firebaseapp.com',
    storageBucket: 'learning-app-c5b3f.appspot.com',
    measurementId: 'G-VQE7DRJ4ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHOyS4gAafDCWwSD_LWCK1mLfWTVStY2Y',
    appId: '1:188574300841:android:21049533dd11fb844d87b8',
    messagingSenderId: '188574300841',
    projectId: 'learning-app-c5b3f',
    storageBucket: 'learning-app-c5b3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIqMBObNhT0yi-gJVTEFj3CHrhoJSy-BU',
    appId: '1:188574300841:ios:092120b7a31cd7b54d87b8',
    messagingSenderId: '188574300841',
    projectId: 'learning-app-c5b3f',
    storageBucket: 'learning-app-c5b3f.appspot.com',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIqMBObNhT0yi-gJVTEFj3CHrhoJSy-BU',
    appId: '1:188574300841:ios:092120b7a31cd7b54d87b8',
    messagingSenderId: '188574300841',
    projectId: 'learning-app-c5b3f',
    storageBucket: 'learning-app-c5b3f.appspot.com',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOryXz6OeSCPPJqNDthEnOyv1-3bwftqQ',
    appId: '1:188574300841:web:8b4a0077fb10ab594d87b8',
    messagingSenderId: '188574300841',
    projectId: 'learning-app-c5b3f',
    authDomain: 'learning-app-c5b3f.firebaseapp.com',
    storageBucket: 'learning-app-c5b3f.appspot.com',
    measurementId: 'G-3TLV55P6ZF',
  );
}
